/**
 * 图标名称类型，svg 文件名去除后缀
 */
export type SpIconName =
  | 'agent-filled'
  | 'alipay-filled'
  | 'angles-right'
  | 'application'
  | 'arrow-down'
  | 'arrow-rotate-left-light'
  | 'arrow-rotate-right-light'
  | 'arrow-rotate-right'
  | 'audio-square'
  | 'bar-filled'
  | 'bar-y-axis-filled'
  | 'bar'
  | 'bottom-filled'
  | 'camera-filled'
  | 'chat-duration-multi'
  | 'chat-transfer-multi'
  | 'chat-connected-multi'
  | 'chat-smile-multi'
  | 'chat-star-multi'
  | 'chat'
  | 'check-all'
  | 'check'
  | 'clear'
  | 'clock-four'
  | 'clock'
  | 'close'
  | 'cloudy'
  | 'contact-log'
  | 'curve-filled'
  | 'customer'
  | 'customer-filled'
  | 'delete'
  | 'digital-panel'
  | 'download-circle'
  | 'download'
  | 'edit'
  | 'email-filled'
  | 'employee-filled'
  | 'exclamation-mark-filled'
  | 'expand'
  | 'export'
  | 'eye-slash'
  | 'filter'
  | 'fold'
  | 'folder'
  | 'flower-filled'
  | 'folder-filled'
  | 'folder-opened-filled'
  | 'funnel-filled'
  | 'gauge'
  | 'globe-filled'
  | 'group'
  | 'home'
  | 'hourglass'
  | 'image'
  | 'import'
  | 'kb'
  | 'keyboard-circle'
  | 'label'
  | 'language'
  | 'line-height'
  | 'line-square'
  | 'line-up'
  | 'line'
  | 'location'
  | 'lock'
  | 'maximize-window'
  | 'message'
  | 'mike'
  | 'minus-circle'
  | 'minus'
  | 'mobile-phone-filled'
  | 'monitor'
  | 'moon-fat-filled'
  | 'more-filled'
  | 'normal'
  | 'notification'
  | 'paperclip'
  | 'pause-circle-filled'
  | 'pause-circle'
  | 'pc-filled'
  | 'phone-arrow-loop-multi'
  | 'phone-arrow-right-multi'
  | 'phone-arrow-right'
  | 'phone-check-multi'
  | 'phone-filled'
  | 'phone-user-multi'
  | 'phone-wave-filled'
  | 'phone-wave-multi'
  | 'pie-filled'
  | 'pie-hollow-filled'
  | 'play-circle-filled'
  | 'play-circle'
  | 'plus-square'
  | 'plus-tag'
  | 'plus'
  | 'pop-screen'
  | 'power-off'
  | 'print'
  | 'promotion'
  | 'radar-filled'
  | 'redo'
  | 'refresh'
  | 'report'
  | 'restored-window'
  | 'robot'
  | 'role-filled'
  | 'search'
  | 'reload-cache'
  | 'selection'
  | 'setting'
  | 'shield-check'
  | 'shirt'
  | 'skill-filled'
  | 'skill-simple-filled'
  | 'smile'
  | 'sms-filled'
  | 'sms'
  | 'soft-phone'
  | 'star-filled'
  | 'summary-clock'
  | 'summary-create'
  | 'sunny-filled'
  | 'suona-multi'
  | 'suona'
  | 'switch'
  | 'table-filled'
  | 'ticket-clock-multi'
  | 'ticket-completed-multi'
  | 'ticket-create-multi'
  | 'ticket-create'
  | 'ticket-filled'
  | 'ticket-submit-multi'
  | 'ticket-transfer-log'
  | 'ticket-user-multi'
  | 'ticket'
  | 'tiktok'
  | 'tips-filled'
  | 'tips'
  | 'top-filled'
  | 'track-filled'
  | 'uncheck-all'
  | 'undo'
  | 'unknown-animate'
  | 'user-plus'
  | 'user'
  | 'video-recorder'
  | 'video-filled'
  | 'warn-bubble-square-filled'
  | 'warning'
  | 'wechat-filled'
  | 'wechat-mini-program-filled'
  | 'wechat-mini-program'
  | 'workspace'
  | 'zoom-in'
  | 'zoom-out'
  | 'zoom-reset';

export interface SpIconProps {
  /**
   * 图标名称
   */
  name: SpIconName;

  /**
   * 图标旋转 transform: rotate(${rotate}); 比较常用的选中 180° 值应为 180deg
   */
  rotate?: string;
  /**
   * 围绕横坐标 (水平轴) 旋转，水平翻转的值应为 180deg
   */
  rotateX?: string;
  /**
   * 围绕纵坐标 (垂直轴) 旋转，垂直翻转的值应为 180deg
   */
  rotateY?: string;
  /**
   * 图标大小
   */
  size?: string;
}
